version: '3.7'
services:
  opensearch-node1:
    image: opensearchproject/opensearch:2.3.0
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1
      - cluster.initial_master_nodes=opensearch-node1
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - plugins.security.allow_default_init_securityindex=true
      - "DISABLE_INSTALL_DEMO_CONFIG=true"  # Wyłączenie konfiguracji demo
      - "DISABLE_SECURITY_PLUGIN=true"  # Wyłączenie zabezpieczeń SSL dla testów
      - "OPENSEARCH_PASSWORD=AdminPassword123"  # Ustawienie hasła dla konta Administrator
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.3.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch-node1:9200"]'  # Użycie HTTP bez SSL
      OPENSEARCH_USERNAME: 'admin'  # Domyślny użytkownik
      OPENSEARCH_PASSWORD: 'AdminPassword123'  # Hasło dla użytkownika
    networks:
      - opensearch-net

volumes:
  opensearch-data1:

networks:
  opensearch-net: